import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import ScreenHeader from '@/components/common/ScreenHeader';
import CampusCard from '@/components/common/CampusCard';
import CampusButton from '@/components/common/CampusButton';
import BottomNavigation from '@/components/common/BottomNavigation';
import { useCampusTheme } from '@/context/ThemeContext';
import { Typography } from '@/constants/typography';

export default function Dashboard(){const router=useRouter();const{colors}=useCampusTheme();return <ScrollView contentContainerStyle={[styles.container,{backgroundColor:colors.background}]}><ScreenHeader title="Good morning" subtitle="Your recovery journey continues" back={false}/><Pressable onPress={()=>router.push('/check-in')} style={[styles.banner,{backgroundColor:colors.greenSoft,borderColor:colors.green}]}><Text style={[Typography.caption,{color:colors.green}]}>DAILY CHECK-IN</Text><Text style={[Typography.h2,{color:colors.textPrimary,marginTop:3}]}>How are you feeling today?</Text><Text style={[Typography.bodySmall,{color:colors.textMuted}]}>Take a moment to check in with yourself.</Text></Pressable><Text style={[Typography.h2,{color:colors.textPrimary,marginTop:20}]}>Wellbeing Snapshot</Text><View style={styles.grid}>{[['PHQ-9','12 / 27'],['GAD-7','10 / 21'],['DASS-21','Moderate'],['WHO-5','46 / 100']].map(([a,b])=><CampusCard key={a} style={styles.metric}><Text style={[Typography.caption,{color:colors.textMuted}]}>{a}</Text><Text style={[Typography.h2,{color:colors.textPrimary,marginTop:5}]}>{b}</Text></CampusCard>)}</View><CampusCard style={{marginTop:10}}><Text style={[Typography.h3,{color:colors.textPrimary}]}>Your Progress</Text><Text style={[Typography.bodySmall,{color:colors.textMuted,marginTop:4}]}>See assessments, check-ins, journal history and trends.</Text><CampusButton title="View monitoring →" onPress={()=>router.push('/dynamic-monitoring')} style={{marginTop:12}}/></CampusCard><CampusCard style={{marginTop:10}}><Text style={[Typography.h3,{color:colors.textPrimary}]}>Journal & Context</Text><Text style={[Typography.bodySmall,{color:colors.textMuted,marginTop:4}]}>Share what's on your mind or update your circumstances when you're ready.</Text><CampusButton title="Open Journal & Context" onPress={()=>router.push('/emotional-expression')} variant="purple" style={{marginTop:12}}/></CampusCard><BottomNavigation/></ScrollView>}
const styles=StyleSheet.create({container:{flexGrow:1,padding:20,paddingTop:38},banner:{borderWidth:1,borderRadius:14,padding:16},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',marginTop:10},metric:{width:'48%',marginBottom:8}});
