import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import ScreenHeader from '@/components/common/ScreenHeader';
import CampusCard from '@/components/common/CampusCard';
import CampusButton from '@/components/common/CampusButton';
import BottomNavigation from '@/components/common/BottomNavigation';
import { useAssessment } from '@/context/AssessmentContext';
import { useCampusTheme } from '@/context/ThemeContext';
import { Typography } from '@/constants/typography';

export default function DynamicMonitoring(){const router=useRouter();const{colors}=useCampusTheme();const{history}=useAssessment();return <ScrollView contentContainerStyle={[styles.container,{backgroundColor:colors.background}]}><ScreenHeader title="Your Progress Over Time" subtitle="See how your wellbeing changes across check-ins and assessments"/><View style={styles.ranges}>{['1W','1M','3M','6M'].map((x,i)=><View key={x} style={[styles.range,{backgroundColor:i===2?colors.green:colors.surfaceSoft}]}><Text style={{color:i===2?colors.background:colors.textPrimary,fontWeight:'800'}}>{x}</Text></View>)}</View><CampusCard><Text style={[Typography.h3,{color:colors.textPrimary}]}>Wellbeing trend</Text><View style={styles.chart}>{history.map((h,i)=><View key={h.id} style={styles.bar}><View style={[styles.dot,{backgroundColor:colors.purpleBright,marginBottom:Math.max(8,50-(h.phq9||0)*2)}]}/><Text style={[Typography.caption,{color:colors.textMuted}]}>{h.date.slice(5)}</Text></View>)}</View><Text style={[Typography.bodySmall,{color:colors.textMuted}]}>Historical results are retained rather than overwritten.</Text></CampusCard><Text style={[Typography.h3,{color:colors.textPrimary,marginTop:18,marginBottom:8}]}>Recent Activity</Text>{history.slice().reverse().map(h=><CampusCard key={h.id} style={{marginBottom:8}}><Text style={[Typography.body,{color:colors.textPrimary,fontWeight:'700'}]}>Assessment • {h.date}</Text><Text style={[Typography.bodySmall,{color:colors.textMuted,marginTop:4}]}>PHQ-9 {h.phq9 ?? '—'}  •  GAD-7 {h.gad7 ?? '—'}  •  WHO-5 {h.who5 ?? '—'}</Text></CampusCard>)}<CampusCard style={{marginTop:8}}><Text style={[Typography.h3,{color:colors.textPrimary}]}>Login & session history</Text><Text style={[Typography.bodySmall,{color:colors.textMuted,marginTop:6}]}>10 Sep • 6:45 PM — 18 min</Text><Text style={[Typography.bodySmall,{color:colors.textMuted}]}>03 Sep • 6:42 PM — 22 min</Text><Text style={[Typography.bodySmall,{color:colors.textMuted}]}>27 Aug • 7:10 PM — 16 min</Text></CampusCard><CampusButton title="View detailed insights →" onPress={()=>router.push('/ai-insights')} style={{marginTop:14}}/><BottomNavigation/></ScrollView>}
const styles=StyleSheet.create({container:{flexGrow:1,padding:20,paddingTop:38},ranges:{flexDirection:'row',gap:7,marginBottom:14},range:{flex:1,padding:10,borderRadius:9,alignItems:'center'},chart:{height:130,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-around',marginVertical:12,borderBottomWidth:1,borderBottomColor:'#263746'},bar:{alignItems:'center',justifyContent:'flex-end',height:'100%'},dot:{width:14,height:14,borderRadius:7}});
